import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import HomeComponet from "@/components/Home/HomeComponent";
import { GetStaticProps, InferGetStaticPropsType } from "next";
import axios from '../services/axios'

const inter = Inter({ subsets: ["latin"] });

 export type blogData = {
  _id?:string;
  title: string;
  content: string;
  author: string;
};

export const getStaticProps:GetStaticProps = async () => { 
  const res= await axios.get<blogData[]>("/blog/allBlog");
  // const res = await fetch('http://localhost:4000/blog/allBlog')
  // const blogs: blogData[] = await res.json()
  const blogs = res.data
  return {
    props: {
      blogs
    },
  };
};

export default function Home({ blogs }: InferGetStaticPropsType<typeof getStaticProps>) {
  console.log(blogs)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
      <HomeComponet blogs={blogs} />
      </>
    </>
  );
}
